version: "2"
services:
  config-server-microservice:
    image: config-server-microservice-jib:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
  eureka-server:
    image: eureka-server-jib:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
  aggregator-microservice:
    image: aggregator-microservice-jib:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment: 
     - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
     - spring.cloud.config.uri= http://config-server-microservice:8888
    depends_on:
      - "eureka-server"
      - "config-server-microservice"
    command: ["./wait-for-it.sh", "config-server-microservice"]
  humidity-microservice:
    image: humidity-microservice-jib:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment: 
     - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
     - spring.cloud.config.uri= http://config-server-microservice:8888
    depends_on:
      - eureka-server
      - config-server-microservice
    command: ["./wait-for-it.sh", "eureka-server:8761"]
    links:
     - eureka-server
  temperature-microservice:
    image: temperature-microservice-jib:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment: 
     - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
     - spring.cloud.config.uri= http://config-server-microservice:8888
    depends_on:
      - "eureka-server"
      - "config-server-microservice"
    command: ["./wait-for-it.sh", "eureka-server:8761"]